# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasisModule' do
 pod 'AFNetworking'
#pod 'MGJRouter'
pod 'SVProgressHUD', '~> 2.0.3'

#pod 'ReactiveObjC', '~> 3.0.0'
pod 'YYCache'
end
